path:
  training_path: "/data/train.csv"
  test_path: "/data/test.csv"
  model_save_path: "/model/model.pkl"
  predictions_save_path: "/prediction_results/results.csv"

params:
  optimizer: "adam"
  tracking_uri_mlflow: "http://127.0.0.1:8080"
